### PR TITLE
"Hello world" exercise.

### PR DESCRIPTION
**Pull request by daddy32**
My first contribution on GitHub, hope everything's OK.

### CODE REVIEW

**Comment by daddy32** [comment]
Added a new commit hopefully fixing the build. Sorry for not branching them together.

**Comment by kytrinyx** [comment]
@daddy32 I'm so sorry your very first GitHub contribution got lost in some sort of communications black hole. That's not a great experience!

I'm going to get this aligned with the current master so I can merge it.

Thank you so much for taking the time to make this contribution!

**Comment by kytrinyx** [comment]
Merged in efdaa9dbc91e10df26494560c24482714ac968b9

Thanks so much (and my apologies again!)

**Comment by daddy32** [comment]
All's well that ends well :)
Thanks for merging.

**Pull request closed without merging**
